name: CI/CD Práctica Final DevOps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: echo "Running unit tests (example)"

      - name: Build Docker container
        run: |
          docker build -t practica-final-devops .
          docker run -d -p 8080:80 practica-final-devops
